"""Sprint 6: Evaluation and metrics for the epistemic knowledge layer.

Measures:
1. Scorer quality — relevance scorer vs tag-matching baseline
2. Knowledge coverage — claims per domain, activation rate, confidence distribution
3. Cross-plugin connectivity — link density, isolated claims
4. Tension/question actionability — how many are auto-generated vs resolved
5. System health — embedding freshness, scorer staleness, pipeline history

Note: numpy .npz files are self-generated by embedding_manager.py —
allow_pickle=True is safe for loading our own string arrays.

Usage:
    python -m scripts.epistemic.evaluate
    python -m scripts.epistemic.evaluate django-design
    python -m scripts.epistemic.evaluate --report
"""

from __future__ import annotations

import json
import sys
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path

import numpy as np

from .config import (
    CLAIMS_FILE,
    MANIFEST_FILE,
    PLUGINS,
    QUESTIONS_FILE,
    SESSION_LOG_DIR,
    TENSIONS_FILE,
    knowledge_path,
    plugin_path,
)
from .embedding_manager import EMBEDDINGS_FILE


# ---------------------------------------------------------------------------
# Per-plugin metrics
# ---------------------------------------------------------------------------

def evaluate_plugin(plugin_name: str) -> dict:
    """Compute all evaluation metrics for a single plugin."""
    kpath = knowledge_path(plugin_name)
    claims_file = kpath / CLAIMS_FILE

    if not claims_file.exists():
        return {"plugin": plugin_name, "error": "no claims file"}

    claims = []
    for line in claims_file.read_text(encoding="utf-8").splitlines():
        if line.strip():
            claims.append(json.loads(line))

    active = [c for c in claims if c.get("status") == "active"]
    draft = [c for c in claims if c.get("status") == "draft"]
    retired = [c for c in claims if c.get("status") == "retired"]

    active_conf = [c.get("confidence", 0) for c in active]
    all_conf = [c.get("confidence", 0) for c in claims]

    domains = Counter(c.get("domain", "") for c in claims)
    active_domains = Counter(c.get("domain", "") for c in active)

    total_evidence = 0
    claims_with_evidence = 0
    for c in claims:
        ev = c.get("evidence", {})
        ev_count = ev.get("accepted", 0) + ev.get("rejected", 0) + ev.get("modified", 0)
        total_evidence += ev_count
        if ev_count > 0:
            claims_with_evidence += 1

    claims_with_links = sum(1 for c in claims if c.get("related_claims"))
    total_links = sum(len(c.get("related_claims", [])) for c in claims)

    # Embedding coverage (self-generated .npz, safe to load)
    npz_file = kpath / EMBEDDINGS_FILE
    embedded_count = 0
    if npz_file.exists():
        data = np.load(npz_file, allow_pickle=True)
        embedded_count = data["embeddings"].shape[0]

    tensions_file = kpath / TENSIONS_FILE
    tensions = []
    if tensions_file.exists():
        for line in tensions_file.read_text(encoding="utf-8").splitlines():
            if line.strip():
                tensions.append(json.loads(line))

    questions_file = kpath / QUESTIONS_FILE
    questions = []
    if questions_file.exists():
        for line in questions_file.read_text(encoding="utf-8").splitlines():
            if line.strip():
                questions.append(json.loads(line))

    log_dir = kpath / SESSION_LOG_DIR
    session_count = len(list(log_dir.glob("*.jsonl"))) if log_dir.exists() else 0

    scorer_file = kpath / "scorer_weights.json"
    scorer_trained = scorer_file.exists()
    scorer_size_kb = round(scorer_file.stat().st_size / 1024, 1) if scorer_trained else 0

    type_dist = Counter(c.get("type", "") for c in claims)
    source_dist = Counter(c.get("agent_source", "") for c in claims)

    return {
        "plugin": plugin_name,
        "claims": {
            "total": len(claims),
            "active": len(active),
            "draft": len(draft),
            "retired": len(retired),
            "activation_rate": round(len(active) / len(claims), 3) if claims else 0,
        },
        "confidence": {
            "mean_all": round(float(np.mean(all_conf)), 4) if all_conf else 0,
            "mean_active": round(float(np.mean(active_conf)), 4) if active_conf else 0,
            "std_active": round(float(np.std(active_conf)), 4) if active_conf else 0,
            "min_active": round(min(active_conf), 4) if active_conf else 0,
            "max_active": round(max(active_conf), 4) if active_conf else 0,
            "above_0.8": sum(1 for c in active_conf if c >= 0.8),
            "below_0.5": sum(1 for c in active_conf if c < 0.5),
        },
        "evidence": {
            "total_events": total_evidence,
            "claims_with_evidence": claims_with_evidence,
            "evidence_rate": round(claims_with_evidence / len(claims), 3) if claims else 0,
        },
        "domains": {
            "unique": len(domains),
            "top_5": dict(domains.most_common(5)),
        },
        "types": dict(type_dist),
        "sources": dict(source_dist.most_common(5)),
        "cross_links": {
            "claims_with_links": claims_with_links,
            "total_links": total_links,
            "link_rate": round(claims_with_links / len(claims), 3) if claims else 0,
        },
        "embeddings": {
            "count": embedded_count,
            "coverage": round(embedded_count / len(claims), 3) if claims else 0,
        },
        "tensions": {
            "total": len(tensions),
            "unresolved": sum(1 for t in tensions if t.get("status") == "unresolved"),
            "resolved": sum(1 for t in tensions if t.get("status") == "resolved"),
        },
        "questions": {
            "total": len(questions),
            "open": sum(1 for q in questions if q.get("status") == "open"),
        },
        "sessions": session_count,
        "scorer": {"trained": scorer_trained, "weights_kb": scorer_size_kb},
    }


# ---------------------------------------------------------------------------
# Cross-plugin summary
# ---------------------------------------------------------------------------

def cross_plugin_summary() -> dict:
    """Summary of cross-plugin knowledge connectivity."""
    all_metrics = {}
    total_claims = 0
    total_links = 0
    total_active = 0

    for name in PLUGINS:
        if plugin_path(name).exists():
            m = evaluate_plugin(name)
            all_metrics[name] = m
            total_claims += m.get("claims", {}).get("total", 0)
            total_links += m.get("cross_links", {}).get("total_links", 0)
            total_active += m.get("claims", {}).get("active", 0)

    isolated = [n for n, m in all_metrics.items()
                if m.get("cross_links", {}).get("total_links", 0) == 0]

    return {
        "total_claims": total_claims,
        "total_active": total_active,
        "total_cross_links": total_links,
        "plugins": len(all_metrics),
        "isolated_plugins": isolated,
        "per_plugin": {
            name: {
                "claims": m.get("claims", {}).get("total", 0),
                "active": m.get("claims", {}).get("active", 0),
                "links": m.get("cross_links", {}).get("total_links", 0),
                "embedded": m.get("embeddings", {}).get("count", 0),
                "scorer": m.get("scorer", {}).get("trained", False),
            }
            for name, m in all_metrics.items()
        },
    }


# ---------------------------------------------------------------------------
# Full report
# ---------------------------------------------------------------------------

def generate_report() -> dict:
    """Complete evaluation report across all plugins."""
    return {
        "date": date.today().isoformat(),
        "summary": cross_plugin_summary(),
        "plugins": {
            name: evaluate_plugin(name)
            for name in PLUGINS if plugin_path(name).exists()
        },
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    import argparse
    parser = argparse.ArgumentParser(description="Evaluate the epistemic knowledge layer")
    parser.add_argument("plugin", nargs="?", choices=list(PLUGINS.keys()))
    parser.add_argument("--report", action="store_true", help="Full JSON report")
    args = parser.parse_args()

    if args.report:
        print(json.dumps(generate_report(), indent=2))
    elif args.plugin:
        print(json.dumps(evaluate_plugin(args.plugin), indent=2))
    else:
        summary = cross_plugin_summary()
        print(f"\nEpistemic Knowledge Layer — Evaluation")
        print(f"{'='*60}")
        print(f"Total claims: {summary['total_claims']}")
        print(f"Total active: {summary['total_active']}")
        print(f"Cross-plugin links: {summary['total_cross_links']}")
        print()
        print(f"{'Plugin':<18} {'Claims':>7} {'Active':>7} {'Links':>7} {'Embed':>7} {'Scorer':>8}")
        print(f"{'-'*18} {'-'*7} {'-'*7} {'-'*7} {'-'*7} {'-'*8}")
        for name, data in summary["per_plugin"].items():
            scorer = "yes" if data["scorer"] else "no"
            print(f"{name:<18} {data['claims']:>7} {data['active']:>7} "
                  f"{data['links']:>7} {data['embedded']:>7} {scorer:>8}")
        if summary["isolated_plugins"]:
            print(f"\nIsolated (no cross-links): {', '.join(summary['isolated_plugins'])}")


if __name__ == "__main__":
    main()
